spring:
  datasource:
    url: ${DB_URL} # jdbc:postgresql://localhost:5432/normative-control
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME}  #postgres
    password: ${DB_PASSWORD} #maeasoftworks
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${AMQP_HOST} #localhost
    password: ${AMQP_PASSWORD} #normativecontrol
    username: ${AMQP_USERNAME} #maeasoftworks
    port: ${AMQP_PORT} #5672
    senderQueueName: ${AMQP_QUEUE} #to_be_verified
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jackson:
    time-zone: Asia/Yekaterinburg

server:
  error:
    include-stacktrace: never
  port: ${API_PORT}
  servlet:
    context-path: ${API_PREFIX}

springdoc:
  swagger-ui:
    operations-sorter: alpha

jwt:
  accessToken:
    key: 267e3dad2f5e22ea927180c740f6c0092d79ac61089845bc25a487f101554808
    lifetimeInSeconds: 2592000 # accessToken's lifetime is 30 days (2592000 seconds)
  refreshToken:
    key: 2e82817a3fe3eb81717c5afdf8f33da3425fbeb81a059f4b377e359adaa66e2e
    lifetimeInSeconds: 2592000 # refreshToken's lifetime is 30 days (2592000 seconds)

normativeControl:
  api:
    domain: normative-control.ru
    host: localhost
    port: 8080
    protocol: http
    url: ${normativeControl.api.protocol}://${normativeControl.api.host}:${normativeControl.api.port}

s3:
  region: ${S3_REGION} #US-EAST-1
  accessKeyId: ${S3_ACCESS_KEY_ID} #pdh5niPCbqYxGW5BKxGv
  secretAccessKey: ${S3_SECRET_ACCESS_KEY} #xqtc6gXpKy0OIZVVSeinxDd7dd0pbDsOEtU7huJX
  endpoint: ${S3_ENDPOINT} #http://localhost:9000
  bucket: ${S3_BUCKET} #normative-control